import type { Project } from '../types';

/**
 * Mock data simulating what would come from the SharePoint list
 * "Base-Projetos-Grandes-Reparos" after being populated from MPP files.
 */
export const mockProjects: Project[] = [
    {
        id: 1,
        title: 'Reforma do Alto-Forno 3',
        coordinator: 'Carlos Silva',
        status: 'Em Andamento',
        startDate: '2026-01-15',
        endDate: '2026-06-30',
        progress: 42,
        budgetCost: 2500000,
        actualCost: 980000,
        comments: 'Fase de desmontagem concluída. Início da reconstrução previsto para março.',
    },
    {
        id: 2,
        title: 'Manutenção Convertedor LD-2',
        coordinator: 'Ana Martins',
        status: 'Atrasado',
        startDate: '2025-11-01',
        endDate: '2026-03-15',
        progress: 65,
        budgetCost: 1800000,
        actualCost: 1350000,
        comments: 'Atraso no fornecimento de refratários. Nova previsão: +30 dias.',
    },
    {
        id: 3,
        title: 'Troca de Rolos - Laminador a Quente',
        coordinator: 'Roberto Almeida',
        status: 'Concluído',
        startDate: '2025-09-01',
        endDate: '2025-12-20',
        progress: 100,
        budgetCost: 950000,
        actualCost: 920000,
        comments: 'Projeto entregue dentro do prazo e orçamento.',
    },
    {
        id: 4,
        title: 'Revamp Linha de Galvanização',
        coordinator: 'Fernanda Costa',
        status: 'Em Andamento',
        startDate: '2026-02-01',
        endDate: '2026-08-31',
        progress: 18,
        budgetCost: 4200000,
        actualCost: 620000,
        comments: 'Engenharia detalhada em andamento. Compra de equipamentos iniciada.',
    },
    {
        id: 5,
        title: 'Reparo Sinter Plant - Esteira 4',
        coordinator: 'Marcos Oliveira',
        status: 'Não Iniciado',
        startDate: '2026-04-01',
        endDate: '2026-07-15',
        progress: 0,
        budgetCost: 1200000,
        actualCost: 0,
        comments: 'Aguardando aprovação do CAPEX.',
    },
    {
        id: 6,
        title: 'Modernização Sistema de Despoeiramento',
        coordinator: 'Juliana Santos',
        status: 'Em Andamento',
        startDate: '2025-10-15',
        endDate: '2026-05-30',
        progress: 55,
        budgetCost: 3100000,
        actualCost: 1600000,
        comments: 'Instalação dos novos filtros em progresso. 3 de 8 unidades concluídas.',
    },
    {
        id: 7,
        title: 'Reparo Ponte Rolante - Aciaria',
        coordinator: 'Paulo Mendes',
        status: 'Pausado',
        startDate: '2026-01-10',
        endDate: '2026-04-20',
        progress: 30,
        budgetCost: 750000,
        actualCost: 210000,
        comments: 'Pausado por questões de segurança. Revisão do plano de rigging necessária.',
    },
    {
        id: 8,
        title: 'Substituição Refratário - Panela 12',
        coordinator: 'Carlos Silva',
        status: 'Concluído',
        startDate: '2025-12-01',
        endDate: '2026-01-25',
        progress: 100,
        budgetCost: 420000,
        actualCost: 415000,
        comments: 'Concluído com sucesso. Vida útil estimada: 18 meses.',
    },
    {
        id: 9,
        title: 'Automação Pátio de Minérios',
        coordinator: 'Ana Martins',
        status: 'Em Andamento',
        startDate: '2025-08-01',
        endDate: '2026-09-30',
        progress: 38,
        budgetCost: 5600000,
        actualCost: 1950000,
        comments: 'Sistema SCADA instalado. Integração com PLCs em fase de testes.',
    },
    {
        id: 10,
        title: 'Recuperação Regenerador - Coqueria',
        coordinator: 'Roberto Almeida',
        status: 'Atrasado',
        startDate: '2025-11-15',
        endDate: '2026-02-28',
        progress: 72,
        budgetCost: 1650000,
        actualCost: 1400000,
        comments: 'Problemas estruturais não previstos. Necessário reforço adicional.',
    },
];
